### PR TITLE
#13 added possibility to open image inside a modal

### PR DESCRIPTION
**Pull request by artifactdev**
Added an imageModal which can be filled from an image to show in in a bigger size.
For opening the image inside modal (espacially the collage at front-page) the image has to become the attrobute "data-ui-image-modal" in the editor.

### CODE REVIEW

**Comment by stefanbethke** [comment]
I don't think we can add classes or attributes to the image tag, at least not without changing Django CMS itself. The `img` tag is wrapped in a span with the classes `plugin_picture` and `align-left`, `align-center` or `align-right`. I think that's all we can work with.

**Comment by artifactdev** [comment]
@stefanbethke I tested in DEV-System there it's a bit different as in actual production-version of the CMS.  The CMS now renders without span tag and has the abbility to add attributes to the image. I tested this directy on the local instance by adding an image to the startpage and giving it the needed attribute.

**Comment by jandd** [comment]
We also have the ability to define custom image style templates via the `DJANGOCMS_PICTURE_TEMPLATES` setting if we see demand for this. See https://github.com/divio/djangocms-picture for documentation and template folder location.

**Comment by stefanbethke** [comment]
Sorry, I was looking at the old code. LGTM.

**Pull request merged**
