### PR TITLE
Switch base image to debian:buster-slim

### PR DESCRIPTION
**Pull request by jandd**
This commit switches the Docker base image to debian:buster-slim. This
change has been made to follow Python Docker best practices described in
https://pythonspeed.com/articles/base-image-python-docker-images/ and
https://pythonspeed.com/articles/alpine-docker-python/.

### CODE REVIEW

**Review by ronnyfriedland — CHANGES_REQUESTED** [review]
I think there is a typo in DEBIAN_FRONTENT -> should be DEBIAN_FRONTEND

**Comment by jandd** [comment]
build fails because of the old Alpine based base image. The whole build process needs rework. This is related to #172

**Review by ronnyfriedland — APPROVED** [review]
👍

**Review by ronnyfriedland — APPROVED** [review]
changes look reasonable to me

**Pull request merged**
